language: rust
cache: cargo
rust:
  - nightly
os:
  - linux
  - osx
deploy:
  provider: releases
  api_key:
    secure: RLFD7NtbuB2yo1pw37IZi5+krP7iwKCGU57q8Cdq1OAg4IyohHseqPI1C7SOJQQCYa23d50viSCkucd/hxnCEDjb33L47mhDSNZE1hWqn53JN4EN4frbijz7R7IwA2Ab5qyYIzCnd/6oacICP4VJtXQwOYTjzi+Ym27umcMyiZ267ASybQi4tZSzjcqvxbgtBZPiI0u0b3GqFZUwsjowTDsKTrqGoEbGvHCG0BNKMPlhjXBsImWgKGmfFSFNrEVE9e8Ip21UXSJqO1pkoR04fVpb+60mWrsihipJY58w6Zk7GFjOC4Kmas/P2tCbfB8ZR665J7+Py6IlMKWcTYF/8qFphHUZUZ7TzO7zrZ9fZhMi8o2D2SUptf2UQavsu3wTjBMn2PY9o12xaZCPjx7YUmYWf5Bgpk72FH7cA6aR7wPB/Db8zGiQm0oeYtVbs/wd5+BDjRmbyYoqv4lnnzvb8xlId5qYN019e2ojDTg7yu58SV2NO6SL1HXHa+HVj+r3ejQoV35tqDYIL+rTQWzumXNlp5KXPishLqiymVwo8CY3hXtBgGUYllaYSDp6e83pzb1VpbeVtqx3r8Scycs/B4yNs2g9elHCtAvWz/PNgDzhzzx0LCqVo8aeG6yrAbZcURTwMtCIWBovoqp6W7rpvxX1beFluA/TMuxnmNFGBBI=
  file: "./target/release/instaclone_backend"
  on:
    repo: sergeysova/instaclone-backend.rs
    tags: true
  skip_cleanup: true

script:
  - cargo build --verbose --release
